branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - path: "@semantic-release/exec"
    verifyConditionsCmd: "semantic-release-rust verify-conditions"
    prepareCmd: "semantic-release-rust prepare ${nextRelease.version}"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo update"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo build --release"
  - path: "@codedependant/semantic-release-docker"
    dockerProject: "timada0"
    dockerImage: "pikav"
  - path: "@semantic-release/git"
    assets:
      - "**/Cargo.toml"
      - Cargo.lock
