[workspace]

resolver = "2"

members = [
    "./cmd",
    "./api",
    "./cluster",
    "./pikav",
    "./pikav-client",
    "./pikav-web",
    "./examples/leptos"
]

[workspace.metadata.cargo-machete]
ignored = ["prost"]

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
strip = true
