[workspace]

resolver = "2"

members = [
    "./cmd",
    "./api",
    "./cluster",
    "./pikav",
    "./pikav-client",
    "./pikav-web",
    "./example"
]

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
strip = true
