version: '3.9'

services:
  fake-jwt-auth-server:
    image: michaelruocco/fake-jwt-auth-server
    container_name: fake-jwt-auth-server
    ports:
      - 6550:80

  pikav:
    image: timayz-dev/pikav
    profiles:
      - standalone
    depends_on:
      - fake-jwt-auth-server
    ports:
      - "6750:6750"
      - "6751:6751"
    volumes:
      - ./configs/standalone.yml:/etc/pikav/config.yml
