[package]
name = "pikav-web"
version = "0.16.0"
edition = "2021"
license = "Apache-2.0"
description = "A client that help you publish to pikav server"
repository = "https://github.com/timada-org/pikav"
homepage = "https://pikav.timada.co"
documentation = "https://docs.rs/pikav-client"

[dependencies]
pikav = { path = "../pikav", features = ["event"], version = "0.16.0" }
anyhow = "1.0.70"
gloo-net = "0.2.6"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
futures = "0.3.28"
wasm-bindgen-futures = { version = "0.4.34", optional = true }
log = { version = "0.4.17", optional = true }
cfg-if = "1.0.0"
leptos = { version = "0.3.0-alpha", default-features = false, features = [
  "serde",
], optional = true }

[features]
default = []
hydrate = ["dep:wasm-bindgen-futures", "dep:log"]
leptos = ["dep:leptos"]
leptos-hydrate = ["dep:leptos", "hydrate"]
