[package]
name = "pikav-cluster"
version = "0.10.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav = { path = "../pikav" ,version ="0.10.1"}
pikav-client = { path = "../pikav-client" ,version ="0.10.1"}

tonic = { version = "0.8.3", features = ["tls"] }
prost = "0.11.6"
prost-types = "0.11.6"
prost-derive = "0.11.6"
bytes = "1.3.0"
tracing = "0.1.35"
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net"] }

[build-dependencies]
tonic-build = { version = "0.8.4", features = ["prost"] }
