[package]
name = "pikav-cluster"
version = "0.15.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav = { path = "../pikav", features = ["publisher"] }
pikav-client = { path = "../pikav-client" }

tonic = { version = "0.9.1", features = ["tls"] }
prost = "0.11.9"
bytes = "1.4.0"
tracing = "0.1.37"
tokio = { version = "1.27.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
