[package]
name = "pikav-cluster"
version = "0.18.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
pikav = { path = "../pikav", features = ["publisher"], version = "0.18.0" }
pikav-client = { path = "../pikav-client", version = "0.18.0" }
tonic = { version = "0.10.0", features = ["tls"] }
prost = "0.12.0"
bytes = "1.4.0"
tracing = "0.1.37"
tokio = { version = "1.32.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net" ] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
