[package]
name = "pikav-cluster"
version = "0.17.5"
edition = "2021"
license = "Apache-2.0"

[dependencies]
pikav = { path = "../pikav", features = ["publisher"], version = "0.17.5" }
pikav-client = { path = "../pikav-client", version = "0.17.5" }
tonic = { version = "0.9", features = ["tls"] }
prost = "0.11"
bytes = "1.4"
tracing = "0.1"
tokio = { version = "1.29", features = [ "rt-multi-thread", "time", "fs", "macros", "net" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
