[package]
name = "cmd"
version = "0.17.1"
edition = "2021"
publish = false

[dependencies]
pikav-api = { path = "../api", version = "0.17.1" }
pikav-cluster = { path = "../cluster", version = "0.17.1" }
pikav-client = { path = "../pikav-client", version = "0.17.1" }
config = "0.13.3"
serde = "1.0.160"
serde_json = "1.0.96"
clap = "4.2.2"
actix-rt = "2.8.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
