[package]
name = "cmd"
version = "0.17.3"
edition = "2021"
publish = false

[dependencies]
pikav-api = { path = "../api", version = "0.17.3" }
pikav-cluster = { path = "../cluster", version = "0.17.3" }
pikav-client = { path = "../pikav-client", version = "0.17.3" }
config = "0.13"
serde = "1.0"
serde_json = "1.0"
clap = "4.2"
actix-rt = "2.8"
tracing = "0.1"
tracing-subscriber = "0.3"
