[package]
name = "cmd"
version = "0.13.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav-api = { path = "../api" }
pikav-cluster = { path = "../cluster" }
pikav-client = { path = "../pikav-client" }

config = "0.13.3"
serde = "1.0.152"
serde_json = "1.0.91"
clap = "4.1.4"
actix-rt = "2.8.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
