[package]
name = "cmd"
version = "0.17.8"
edition = "2021"
license = "Apache-2.0"

[dependencies]
pikav-api = { path = "../api", version = "0.17.8" }
pikav-cluster = { path = "../cluster", version = "0.17.8" }
pikav-client = { path = "../pikav-client", version = "0.17.8" }
config = "0.13.3"
serde = "1.0.185"
serde_json = "1.0.105"
clap = "4.3.24"
actix-rt = "2.8.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
