[package]
name = "cmd"
version = "0.17.9"
edition = "2021"
license = "Apache-2.0"

[dependencies]
pikav-api = { path = "../api", version = "0.17.9" }
pikav-cluster = { path = "../cluster", version = "0.17.9" }
pikav-client = { path = "../pikav-client", version = "0.17.9" }
config = "0.13.3"
serde = "1.0.188"
serde_json = "1.0.105"
clap = "4.4.0"
actix-rt = "2.9.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
