[package]
name = "cmd"
version = "0.20.8"
edition = "2021"
license = "Apache-2.0"

[dependencies]
pikav-api = { path = "../api", version = "0.20.8" }
pikav-cluster = { path = "../cluster", version = "0.20.8" }
pikav-client = { path = "../pikav-client", version = "0.20.8" }
config = "0.13.4"
serde = "1.0.195"
serde_json = "1.0.111"
clap = "4.4.13"
actix-rt = "2.9.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
