[package]
name = "pikav-client"
version = "0.13.2"
edition = "2021"
license = "Apache-2.0"
description = "A client that help you publish to pikav server"
repository = "https://github.com/timada-org/pikav"
homepage = "https://pikav.timada.co"
documentation = "https://docs.rs/pikav-client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
parking_lot = "0.12.1"
tokio = "1.27.0"
tracing = "0.1.37"
thiserror = "1.0.40"
tonic = { version = "0.9.1", features = ["tls"] }
prost = "0.11.9"
prost-types = "0.11.9"
prost-derive = "0.11.9"
url = "2.3.1"

[build-dependencies]
tonic-build = { version = "0.9.1", features = ["prost"] }
