[package]
name = "pikav-client"
version = "0.17.3"
edition = "2021"
license = "Apache-2.0"
description = "A client that help you publish to pikav server"
repository = "https://github.com/timada-org/pikav"
homepage = "https://pikav.timada.co"
documentation = "https://docs.rs/pikav-client"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
tokio = "1.27"
tracing = "0.1"
thiserror = "1.0"
tonic = { version = "0.9", features = ["tls"] }
prost = "0.11"
prost-types = "0.11"
prost-derive = "0.11"
url = "2.3"

[build-dependencies]
tonic-build = { version = "0.9", features = ["prost"] }
