addr:
  api: "0.0.0.0:6760"
  cluster: "[::1]:6761"

cors:
  permissive: true

jwks:
  enable: false
  url: http://127.0.0.1:6550/.well-known/jwks.json

nodes:
  - http://[::1]:6751?same_region=true
  - http://[::1]:6771
