addr:
  api: "0.0.0.0:6750"
  cluster: "0.0.0.0:6751"

cors:
  permissive: true

jwks:
  url: http://127.0.0.1:6550/.well-known/jwks.json

nodes:
  - http://127.0.0.1:6761?same_region=true
  - http://127.0.0.1:6771
