addr:
  api: "0.0.0.0:6770"
  cluster: "0.0.0.0:6771"

cors:
  permissive: true

jwks:
  url: http://127.0.0.1:6550/.well-known/jwks.json
  insecure: true

nodes:
  - http://127.0.0.1:6751
  - http://127.0.0.1:6761
