[package]
name = "pikav-api"
version = "0.17.1"
edition = "2021"
publish = false

[dependencies]
pikav = { path = "../pikav", version = "0.17.1" }
pikav-client = { path = "../pikav-client", version = "0.17.1" }
actix-web = "4.3"
actix-cors = "0.6"
serde = "1.0"
serde_json = "1.0"
futures-core = "0.3"
futures-util = "0.3"
thiserror = "1.0"
parking_lot = "0.12"
tracing = "0.1"
twa-jwks = { version = "1.1", features = ["actix-web"] }
