[package]
name = "pikav-api"
version = "0.20.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
pikav = { path = "../pikav", version = "0.20.0" }
pikav-client = { path = "../pikav-client", version = "0.20.0" }
actix-web = "4.4.0"
actix-cors = "0.6.4"
serde = "1.0.188"
serde_json = "1.0.107"
futures-core = "0.3.28"
futures-util = "0.3.28"
thiserror = "1.0.49"
tracing = "0.1.37"
twa-jwks = { version = "1.2.2", features = ["actix-web"] }
