[package]
name = "pikav-api"
version = "0.13.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav = { path = "../pikav" }
pikav-client = { path = "../pikav-client" }

actix-web = "4.3.1"
actix-cors = "0.6.4"
serde = "1.0.160"
serde_json = "1.0.96"
futures-core = "0.3.28"
futures-util = "0.3.28"
thiserror = "1.0.40"
parking_lot = "0.12.1"
tracing = "0.1.37"
lazy_static = "1.4.0"
actix-jwks = "0.2.1"
