[package]
name = "pikav-api"
version = "0.17.0"
edition = "2021"
publish = false

[dependencies]
pikav = { path = "../pikav", version = "0.17.0" }
pikav-client = { path = "../pikav-client", version = "0.17.0" }
actix-web = "4.3.1"
actix-cors = "0.6.4"
serde = "1.0.160"
serde_json = "1.0.96"
futures-core = "0.3.28"
futures-util = "0.3.28"
thiserror = "1.0.40"
parking_lot = "0.12.1"
tracing = "0.1.37"
actix-jwks = "0.2.1"
