[package]
name = "pikav-api"
version = "0.12.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav = { path = "../pikav" }
pikav-client = { path = "../pikav-client" }

actix-web = "4.3.0"
actix-cors = "0.6.4"
serde = "1.0.152"
serde_json = "1.0.91"
futures-core = "0.3.25"
futures-util = "0.3.25"
thiserror = "1.0.38"
parking_lot = "0.12.1"
tracing = "0.1.37"
lazy_static = "1.4.0"
actix-jwks = "0.1.1"
