[package]
name = "pikav-api"
version = "0.20.5"
edition = "2021"
license = "Apache-2.0"

[dependencies]
pikav = { path = "../pikav", version = "0.20.5" }
pikav-client = { path = "../pikav-client", version = "0.20.5" }
actix-web = "4.4.0"
actix-cors = "0.6.5"
serde = "1.0.193"
serde_json = "1.0.108"
futures-core = "0.3.29"
futures-util = "0.3.29"
thiserror = "1.0.50"
tracing = "0.1.40"
twa-jwks = { version = "1.2.7", features = ["actix-web"] }
