name: Publish

on:
  push:
    branches:
      - main
    paths-ignore: 
      - "**/Cargo.toml"
      - "Cargo.lock"
    tags:
      - '*'

jobs:
  docker:
    uses: timayz/.github/.github/workflows/docker.yml@v3
    with:
      image: timayz/pikav
      push: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  cargo:
    uses: timayz/.github/.github/workflows/cargo-publish.yml@v3
    with:
      publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
