name: Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * 1

jobs:
  audit:
    uses: timayz/.github/.github/workflows/rust-audit.yml@chore/renovate/bump-version

  renovate:
    uses: timayz/.github/.github/workflows/renovate.yml@chore/renovate/bump-version
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
